version: "3.9"
services:
  php-apache:
    ports:
      - "8088:80"
    build: './build/php'
    volumes:
      - ./app:/var/www/html
  mysql:
    ports:
      - "3306:3306"
    build: './build/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: "myrootpassword"
      MYSQL_DATABASE: "mysqldb"
      MYSQL_USER: jose
      MYSQL_PASSWORD: 123456
    volumes:
      - dbData:/var/lib/mysql
volumes:
  app:
  dbData: